apiVersion: v1
kind: Service
metadata:
  name: hello-mysql-docker-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: hello-mysql-docker
  type: LoadBalancer